'use strict';
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');

const ROOT=__dirname, DATA_DIR=path.join(ROOT,'data'), DB_FILE=path.join(DATA_DIR,'itznails.db');
fs.mkdirSync(DATA_DIR,{recursive:true});
const db=new DatabaseSync(DB_FILE); db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');

function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}
function verifyPassword(password,stored){const [salt,key]=stored.split(':');return crypto.timingSafeEqual(Buffer.from(key,'hex'),crypto.scryptSync(password,salt,64))}
function migrate(){
 db.exec(`
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,admin_id INTEGER NOT NULL REFERENCES admins(id) ON DELETE CASCADE,expires_at TEXT NOT NULL,csrf_token TEXT NOT NULL DEFAULT '');
 CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY,category_id INTEGER NOT NULL REFERENCES categories(id),name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',price_cents INTEGER NOT NULL CHECK(price_cents>=0),price_label TEXT NOT NULL DEFAULT '',duration_minutes INTEGER NOT NULL CHECK(duration_minutes>0),buffer_minutes INTEGER NOT NULL DEFAULT 0,icon TEXT NOT NULL DEFAULT '✦',active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS service_variants(id INTEGER PRIMARY KEY,service_id INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,name TEXT NOT NULL,price_cents INTEGER NOT NULL,duration_minutes INTEGER,sort_order INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS business_hours(day_of_week INTEGER PRIMARY KEY CHECK(day_of_week BETWEEN 0 AND 6),is_open INTEGER NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY,service_id INTEGER NOT NULL REFERENCES services(id),variant_id INTEGER REFERENCES service_variants(id),client_name TEXT NOT NULL,client_phone TEXT NOT NULL,client_email TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',appointment_date TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,duration_minutes INTEGER NOT NULL,price_cents INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','completed','cancelled','no_show')),source TEXT NOT NULL DEFAULT 'web',whatsapp_status TEXT NOT NULL DEFAULT 'not_sent',whatsapp_message_id TEXT NOT NULL DEFAULT '',confirmed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_appointments_slot ON appointments(appointment_date,start_time,end_time,status);
 CREATE TABLE IF NOT EXISTS blocked_periods(id INTEGER PRIMARY KEY,title TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS portfolio(id INTEGER PRIMARY KEY,title TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT '',image_data TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 `);
 const appointmentSql=db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='appointments'").get()?.sql||'';
 if(!appointmentSql.includes("'pending'")){db.exec(`PRAGMA foreign_keys=OFF; ALTER TABLE appointments RENAME TO appointments_legacy; CREATE TABLE appointments(id INTEGER PRIMARY KEY,service_id INTEGER NOT NULL REFERENCES services(id),variant_id INTEGER REFERENCES service_variants(id),client_name TEXT NOT NULL,client_phone TEXT NOT NULL,client_email TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',appointment_date TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL,duration_minutes INTEGER NOT NULL,price_cents INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','confirmed','completed','cancelled','no_show')),source TEXT NOT NULL DEFAULT 'web',whatsapp_status TEXT NOT NULL DEFAULT 'not_sent',whatsapp_message_id TEXT NOT NULL DEFAULT '',confirmed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO appointments(id,service_id,variant_id,client_name,client_phone,client_email,notes,appointment_date,start_time,end_time,duration_minutes,price_cents,status,source,created_at,updated_at) SELECT id,service_id,variant_id,client_name,client_phone,client_email,notes,appointment_date,start_time,end_time,duration_minutes,price_cents,status,source,created_at,updated_at FROM appointments_legacy; DROP TABLE appointments_legacy; CREATE INDEX idx_appointments_slot ON appointments(appointment_date,start_time,end_time,status); PRAGMA foreign_keys=ON;`)}
 if(!db.prepare("PRAGMA table_info(portfolio)").all().some(c=>c.name==='description'))db.exec("ALTER TABLE portfolio ADD COLUMN description TEXT NOT NULL DEFAULT ''");
 if(!db.prepare("PRAGMA table_info(sessions)").all().some(c=>c.name==='csrf_token')){db.exec("ALTER TABLE sessions ADD COLUMN csrf_token TEXT NOT NULL DEFAULT ''; DELETE FROM sessions;")}
 if(!db.prepare('SELECT 1 FROM admins LIMIT 1').get()){const initialPassword=process.env.ADMIN_PASSWORD||'ItzNails2026!';if(!process.env.ADMIN_PASSWORD)console.warn('AVISO: ADMIN_PASSWORD no está configurada; se usará la contraseña inicial temporal.');db.prepare('INSERT INTO admins(name,email,password_hash) VALUES(?,?,?)').run('Itzel','admin@itznails.local',hashPassword(initialPassword));}
 if(!db.prepare('SELECT 1 FROM categories LIMIT 1').get())seed();
 for(let d=0;d<7;d++)db.prepare('INSERT OR IGNORE INTO business_hours VALUES(?,?,?,?)').run(d,d===1?0:1,d===0?'10:00':'09:00',d===0?'16:00':'19:00');
}
function seed(){
 const cats=['Cabello','Uñas','Cejas y pestañas','Depilación','Maquillaje','Facial'];cats.forEach((n,i)=>db.prepare('INSERT INTO categories(name,sort_order) VALUES(?,?)').run(n,i));
 const cid=Object.fromEntries(db.prepare('SELECT id,name FROM categories').all().map(x=>[x.name,x.id]));
 const items=[
 ['Cabello','Corte de hombre',120,10,'✂',''],['Cabello','Corte de mujer',180,20,'✂',''],['Cabello','Aplicación de tintes',280,120,'◒','Desde $280'],['Cabello','Rayitos o luces',400,300,'✦','Desde $400'],['Cabello','Balayage',700,300,'✦','Desde $700'],['Cabello','Alaciado express',120,30,'〰','Desde $120'],['Cabello','Alaciado permanente',700,300,'〰','Desde $700'],['Cabello','Rizado permanente',400,120,'◌','Desde $400'],['Cabello','Decoloración',500,360,'◐','Valoración previa'],['Cabello','Tratamiento capilar',100,60,'♢','Desde $100'],
 ['Uñas','Uñas acrílicas',220,120,'♡','Desde $220'],['Uñas','Gel semipermanente',180,60,'◇',''],['Uñas','Ruber',180,60,'◇','Desde $180'],['Cejas y pestañas','Rizado de pestañas',100,30,'⌒',''],['Cejas y pestañas','Laminado de cejas',100,30,'⌁',''],['Cejas y pestañas','Laminado + depilación',150,45,'⌁',''],['Depilación','Depilación con cera',40,20,'◦','Desde $40'],['Maquillaje','Peinado',300,60,'♕','Desde $300'],['Maquillaje','Maquillaje',300,60,'✧','Desde $300'],['Maquillaje','Peinado y maquillaje',600,120,'✧','Desde $600'],['Facial','Limpieza facial profunda',220,60,'☼','']];
 const ins=db.prepare('INSERT INTO services(category_id,name,price_cents,duration_minutes,icon,price_label,sort_order) VALUES(?,?,?,?,?,?,?)');items.forEach((x,i)=>ins.run(cid[x[0]],x[1],x[2]*100,x[3],x[4],x[5],i));
 const variants={
  'Aplicación de tintes':[['Corto',280],['Mediano',300],['Largo',380],['Extra largo',450]],'Rayitos o luces':[['Hombre',400],['Corto',500],['Mediano',700],['Largo',900]],'Balayage':[['Corto',700],['Mediano',900],['Largo',1300],['Extra largo',1500]],'Uñas acrílicas':[['Largo #1',220],['Largo #2',250],['Largo #3',280],['Largo #4',300]],'Gel semipermanente':[['Manos',180],['Pies',150],['Manos y pies',300]],'Alaciado express':[['Corto',120],['Mediano',150],['Largo',180],['Extra largo',200]],'Peinado y maquillaje':[['Sencillo',600],['Cargado',700]],'Rizado permanente':[['Hombre',400],['Corto',600],['Mediano',800],['Largo',1000],['Extra largo',1200]],'Depilación con cera':[['Cejas sin diseño',40],['Cejas con diseño',50],['Bozo',40],['Patillas',50],['Nuca baja',50],['Axilas',60]]};
  const get=db.prepare('SELECT id,duration_minutes FROM services WHERE name=?'),vin=db.prepare('INSERT INTO service_variants(service_id,name,price_cents,duration_minutes,sort_order) VALUES(?,?,?,?,?)');Object.entries(variants).forEach(([name,vs])=>{const s=get.get(name);vs.forEach((v,i)=>vin.run(s.id,v[0],v[1]*100,s.duration_minutes,i))});
}
migrate();
function validAdminRoute(value){return /^\/[A-Za-z0-9_-]{8,80}$/.test(value||'')}
let ADMIN_ROUTE=process.env.ADMIN_ROUTE;
if(!validAdminRoute(ADMIN_ROUTE)){if(process.env.RAILWAY_ENVIRONMENT){const saved=db.prepare("SELECT value FROM settings WHERE key='admin_route'").get();ADMIN_ROUTE=saved?.value||`/control-${crypto.randomBytes(8).toString('hex')}`;db.prepare("INSERT OR REPLACE INTO settings(key,value) VALUES('admin_route',?)").run(ADMIN_ROUTE)}else ADMIN_ROUTE='/admin.html'}

const securityHeaders={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"};
const json=(res,status,body,headers={})=>{res.writeHead(status,{...securityHeaders,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(body))};
const error=(res,status,message)=>json(res,status,{error:message});
async function body(req){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>8*1024*1024)throw Object.assign(new Error('Solicitud demasiado grande'),{status:413});chunks.push(c)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString())}catch{throw Object.assign(new Error('JSON inválido'),{status:400})}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[decodeURIComponent(x.slice(0,i).trim()),decodeURIComponent(x.slice(i+1))]}))}
const sessionCookie=()=>process.env.RAILWAY_ENVIRONMENT?'__Host-itz_session':'itz_session';
function admin(req){const token=cookies(req)[sessionCookie()];if(!token)return null;return db.prepare(`SELECT a.id,a.name,a.email,s.csrf_token FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).get(crypto.createHash('sha256').update(token).digest('hex'))}
function requireAdmin(req,res){const a=admin(req);if(!a)error(res,401,'Inicia sesión para continuar');return a}
function serviceRows(activeOnly=true){const rows=db.prepare(`SELECT s.*,c.name category FROM services s JOIN categories c ON c.id=s.category_id ${activeOnly?'WHERE s.active=1':''} ORDER BY c.sort_order,s.sort_order,s.name`).all();const vs=db.prepare('SELECT * FROM service_variants ORDER BY sort_order').all();return rows.map(s=>({...s,variants:vs.filter(v=>v.service_id===s.id)}))}
function toMin(t){const[a,b]=t.split(':').map(Number);return a*60+b} function fromMin(m){return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function availability(date,serviceId,variantId){const s=db.prepare('SELECT * FROM services WHERE id=? AND active=1').get(serviceId);if(!s)throw Object.assign(new Error('Servicio no disponible'),{status:404});let duration=s.duration_minutes+s.buffer_minutes;if(variantId){const v=db.prepare('SELECT * FROM service_variants WHERE id=? AND service_id=?').get(variantId,serviceId);if(!v)throw Object.assign(new Error('Variante inválida'),{status:400});duration=(v.duration_minutes||s.duration_minutes)+s.buffer_minutes}
 const dow=new Date(`${date}T12:00:00`).getDay(),h=db.prepare('SELECT * FROM business_hours WHERE day_of_week=?').get(dow);if(!h?.is_open)return[];
 const busy=db.prepare(`SELECT start_time,end_time FROM appointments WHERE appointment_date=? AND status IN ('pending','confirmed','completed')`).all(date).map(x=>[toMin(x.start_time),toMin(x.end_time)]);
 const blocks=db.prepare(`SELECT start_at,end_at FROM blocked_periods WHERE date(start_at)<=? AND date(end_at)>=?`).all(date,date).map(x=>[new Date(x.start_at).getHours()*60+new Date(x.start_at).getMinutes(),new Date(x.end_at).getHours()*60+new Date(x.end_at).getMinutes()]);
 const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,minNow=now.getHours()*60+now.getMinutes()+30,out=[];for(let t=toMin(h.start_time);t+duration<=toMin(h.end_time);t+=30){if(date===today&&t<minNow)continue;if(![...busy,...blocks].some(([a,b])=>t<b&&t+duration>a))out.push(fromMin(t))}return out;
}
function validDate(x){return /^\d{4}-\d{2}-\d{2}$/.test(x)} function validTime(x){return /^([01]\d|2[0-3]):[0-5]\d$/.test(x)}
const loginAttempts=new Map();
function requestIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function loginKey(req,email){return `${requestIp(req)}:${String(email||'').trim().toLowerCase()}`}
function loginAllowed(key){const a=loginAttempts.get(key);if(!a)return true;if(a.blockedUntil>Date.now())return false;if(Date.now()-a.firstAt>15*60_000){loginAttempts.delete(key);return true}return true}
function failedLogin(key){const now=Date.now(),old=loginAttempts.get(key);const a=!old||now-old.firstAt>15*60_000?{count:1,firstAt:now,blockedUntil:0}:{...old,count:old.count+1};if(a.count>=5)a.blockedUntil=now+15*60_000;loginAttempts.set(key,a)}
function validCsrf(req,a){const token=String(req.headers['x-csrf-token']||'');if(!token||!a.csrf_token||token.length!==a.csrf_token.length)return false;return crypto.timingSafeEqual(Buffer.from(token),Buffer.from(a.csrf_token))}
function sameOrigin(req){const site=req.headers['sec-fetch-site'];if(site==='cross-site')return false;const origin=req.headers.origin;if(!origin)return true;try{return new URL(origin).host===req.headers.host}catch{return false}}
function whatsappNumber(phone){let digits=String(phone||'').replace(/\D/g,'');if(digits.length===10)digits='52'+digits;return digits}
function confirmationText(a){return `Hola ${a.client_name} ✨ Tu cita en Itzz Nails ha sido confirmada.\n\nServicio: ${a.service_name}${a.variant_name?' - '+a.variant_name:''}\nFecha: ${a.appointment_date}\nHora: ${a.start_time}\n\n¡Te esperamos!`}
async function sendWhatsAppConfirmation(a){const to=whatsappNumber(a.client_phone),encodedText=encodeURIComponent(confirmationText(a)),manualUrl=`https://web.whatsapp.com/send?phone=${to}&text=${encodedText}`,appUrl=`whatsapp://send?phone=${to}&text=${encodedText}`;const token=process.env.WHATSAPP_TOKEN,phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID,template=process.env.WHATSAPP_TEMPLATE_NAME;if(!token||!phoneId||!template)return{status:'manual_required',manualUrl,appUrl};
 const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0',payload={messaging_product:'whatsapp',to,type:'template',template:{name:template,language:{code:process.env.WHATSAPP_TEMPLATE_LANGUAGE||'es_MX'},components:[{type:'body',parameters:[{type:'text',text:a.client_name},{type:'text',text:a.service_name+(a.variant_name?' - '+a.variant_name:'')},{type:'text',text:a.appointment_date},{type:'text',text:a.start_time}]}]}};
 try{const r=await fetch(`https://graph.facebook.com/${version}/${phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error?.message||'Meta rechazó el mensaje');return{status:'sent',messageId:d.messages?.[0]?.id||'',manualUrl,appUrl}}catch(e){console.error('WhatsApp:',e.message);return{status:'failed',error:e.message,manualUrl,appUrl}}
}
async function api(req,res,url){const p=url.pathname,m=req.method;
 if(p==='/api/health'&&m==='GET')return json(res,200,{status:'ok',service:'Itzz Nails'});
 if(p==='/api/public'&&m==='GET')return json(res,200,{services:serviceRows(),hours:db.prepare('SELECT * FROM business_hours ORDER BY day_of_week').all(),portfolio:db.prepare('SELECT * FROM portfolio ORDER BY sort_order,created_at DESC').all()});
 if(p==='/api/availability'&&m==='GET'){const date=url.searchParams.get('date'),sid=+url.searchParams.get('serviceId'),vid=+(url.searchParams.get('variantId')||0);if(!validDate(date||''))return error(res,400,'Fecha inválida');return json(res,200,{slots:availability(date,sid,vid)});}
 if(p==='/api/appointments'&&m==='POST'){const b=await body(req),s=db.prepare('SELECT * FROM services WHERE id=? AND active=1').get(+b.serviceId);if(!s||!validDate(b.date||'')||!validTime(b.time||'')||!String(b.name||'').trim()||String(b.phone||'').replace(/\D/g,'').length<8)return error(res,400,'Revisa los datos de la cita');let v=null;if(b.variantId)v=db.prepare('SELECT * FROM service_variants WHERE id=? AND service_id=?').get(+b.variantId,s.id);const dur=(v?.duration_minutes||s.duration_minutes)+s.buffer_minutes,price=v?.price_cents||s.price_cents,end=fromMin(toMin(b.time)+dur);
  db.exec('BEGIN IMMEDIATE');try{if(!availability(b.date,s.id,v?.id).includes(b.time))throw Object.assign(new Error('Ese horario acaba de ocuparse. Elige otro.'),{status:409});const r=db.prepare(`INSERT INTO appointments(service_id,variant_id,client_name,client_phone,client_email,notes,appointment_date,start_time,end_time,duration_minutes,price_cents,source) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(s.id,v?.id||null,String(b.name).trim().slice(0,100),String(b.phone).trim().slice(0,30),String(b.email||'').trim().slice(0,120),String(b.notes||'').trim().slice(0,500),b.date,b.time,end,dur,price,b.source==='admin'?'admin':'web');db.exec('COMMIT');return json(res,201,{id:Number(r.lastInsertRowid),endTime:end});}catch(e){db.exec('ROLLBACK');throw e}}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(req),key=loginKey(req,b.email);if(!loginAllowed(key))return error(res,429,'Demasiados intentos. Espera 15 minutos.');const a=db.prepare('SELECT * FROM admins WHERE lower(email)=lower(?)').get(String(b.email||''));if(!a||!verifyPassword(String(b.password||''),a.password_hash)){failedLogin(key);return error(res,401,'Correo o contraseña incorrectos')}loginAttempts.delete(key);db.prepare("DELETE FROM sessions WHERE expires_at<=datetime('now') OR admin_id=?").run(a.id);const token=crypto.randomBytes(32).toString('base64url'),hash=crypto.createHash('sha256').update(token).digest('hex'),csrf=crypto.randomBytes(32).toString('base64url');db.prepare(`INSERT INTO sessions(token_hash,admin_id,expires_at,csrf_token) VALUES(?,?,datetime('now','+8 hours'),?)`).run(hash,a.id,csrf);const secure=process.env.RAILWAY_ENVIRONMENT?'; Secure':'';return json(res,200,{admin:{id:a.id,name:a.name,email:a.email},csrfToken:csrf},{'Set-Cookie':`${sessionCookie()}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${secure}`});}
 if(p==='/api/auth/logout'&&m==='POST'){const t=cookies(req)[sessionCookie()];if(t)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(crypto.createHash('sha256').update(t).digest('hex'));const secure=process.env.RAILWAY_ENVIRONMENT?'; Secure':'';return json(res,200,{ok:true},{'Set-Cookie':`${sessionCookie()}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secure}`});}
 if(p==='/api/admin/me'&&m==='GET'){const a=requireAdmin(req,res);if(a)return json(res,200,{admin:{id:a.id,name:a.name,email:a.email},csrfToken:a.csrf_token});return}
 const a=requireAdmin(req,res);if(!a)return;
 if(!['GET','HEAD','OPTIONS'].includes(m)&&(!sameOrigin(req)||!validCsrf(req,a)))return error(res,403,'Solicitud administrativa no válida');
 if(p==='/api/admin/dashboard'&&m==='GET'){const from=url.searchParams.get('from')||new Date().toISOString().slice(0,10),to=url.searchParams.get('to')||'9999-12-31';const appts=db.prepare(`SELECT a.*,s.name service_name,v.name variant_name FROM appointments a JOIN services s ON s.id=a.service_id LEFT JOIN service_variants v ON v.id=a.variant_id WHERE a.appointment_date BETWEEN ? AND ? ORDER BY a.appointment_date,a.start_time`).all(from,to);return json(res,200,{appointments:appts,blocks:db.prepare(`SELECT * FROM blocked_periods WHERE date(start_at)<=? AND date(end_at)>=? ORDER BY start_at`).all(to,from)});}
 if(p==='/api/admin/services'&&m==='GET')return json(res,200,{services:serviceRows(false),categories:db.prepare('SELECT * FROM categories ORDER BY sort_order').all()});
 if(p==='/api/admin/services'&&m==='POST'){const b=await body(req);if(!b.name||+b.durationMinutes<1||+b.price<0)return error(res,400,'Datos de servicio inválidos');const r=db.prepare(`INSERT INTO services(category_id,name,description,price_cents,price_label,duration_minutes,buffer_minutes,icon,active,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(+b.categoryId,String(b.name).trim(),String(b.description||''),Math.round(+b.price*100),String(b.priceLabel||''),+b.durationMinutes,+b.bufferMinutes||0,String(b.icon||'✦'),b.active===false?0:1,999);return json(res,201,{id:Number(r.lastInsertRowid)});}
 let match=p.match(/^\/api\/admin\/services\/(\d+)$/);if(match&&m==='PUT'){const b=await body(req);db.prepare(`UPDATE services SET category_id=?,name=?,description=?,price_cents=?,price_label=?,duration_minutes=?,buffer_minutes=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(+b.categoryId,String(b.name).trim(),String(b.description||''),Math.round(+b.price*100),String(b.priceLabel||''),+b.durationMinutes,+b.bufferMinutes||0,b.active?1:0,+match[1]);return json(res,200,{ok:true});}
 if(p==='/api/admin/hours'&&m==='PUT'){const b=await body(req);if(!Array.isArray(b.hours)||b.hours.length!==7)return error(res,400,'Horario inválido');db.exec('BEGIN');try{const q=db.prepare('UPDATE business_hours SET is_open=?,start_time=?,end_time=? WHERE day_of_week=?');b.hours.forEach(h=>q.run(h.is_open?1:0,h.start_time,h.end_time,h.day_of_week));db.exec('COMMIT');return json(res,200,{ok:true})}catch(e){db.exec('ROLLBACK');throw e}}
 match=p.match(/^\/api\/admin\/appointments\/(\d+)\/confirm$/);if(match&&m==='POST'){const appointment=db.prepare(`SELECT a.*,s.name service_name,v.name variant_name FROM appointments a JOIN services s ON s.id=a.service_id LEFT JOIN service_variants v ON v.id=a.variant_id WHERE a.id=?`).get(+match[1]);if(!appointment)return error(res,404,'Cita no encontrada');if(appointment.status==='cancelled')return error(res,409,'No se puede confirmar una cita cancelada');db.prepare("UPDATE appointments SET status='confirmed',confirmed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(appointment.id);const wa=await sendWhatsAppConfirmation(appointment);db.prepare('UPDATE appointments SET whatsapp_status=?,whatsapp_message_id=? WHERE id=?').run(wa.status,wa.messageId||'',appointment.id);return json(res,200,{ok:true,whatsapp:wa});}
 match=p.match(/^\/api\/admin\/appointments\/(\d+)$/);if(match&&m==='PATCH'){const b=await body(req);if(!['pending','confirmed','completed','cancelled','no_show'].includes(b.status))return error(res,400,'Estado inválido');db.prepare('UPDATE appointments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.status,+match[1]);return json(res,200,{ok:true});}
 if(p==='/api/admin/blocks'&&m==='POST'){const b=await body(req);if(!b.startAt||!b.endAt||new Date(b.endAt)<=new Date(b.startAt))return error(res,400,'Bloqueo inválido');const r=db.prepare('INSERT INTO blocked_periods(title,start_at,end_at) VALUES(?,?,?)').run(String(b.title||'No disponible'),b.startAt,b.endAt);return json(res,201,{id:Number(r.lastInsertRowid)});}
 match=p.match(/^\/api\/admin\/blocks\/(\d+)$/);if(match&&m==='DELETE'){db.prepare('DELETE FROM blocked_periods WHERE id=?').run(+match[1]);return json(res,200,{ok:true});}
 if(p==='/api/admin/portfolio'&&m==='POST'){const b=await body(req);if(!String(b.imageData||'').startsWith('data:image/')||String(b.imageData).length>7_500_000)return error(res,400,'Imagen inválida o demasiado grande');const r=db.prepare('INSERT INTO portfolio(title,category,description,image_data) VALUES(?,?,?,?)').run(String(b.title||'Trabajo realizado').trim().slice(0,100),String(b.category||'').trim().slice(0,60),String(b.description||'').trim().slice(0,350),b.imageData);return json(res,201,{id:Number(r.lastInsertRowid)});}
 match=p.match(/^\/api\/admin\/portfolio\/(\d+)$/);if(match&&m==='DELETE'){db.prepare('DELETE FROM portfolio WHERE id=?').run(+match[1]);return json(res,200,{ok:true});}
 return error(res,404,'Ruta no encontrada');
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(url.pathname==='/admin.html'&&ADMIN_ROUTE!=='/admin.html')return error(res,404,'Página no encontrada');let file=url.pathname==='/'?'index.html':url.pathname===ADMIN_ROUTE?'admin.html':decodeURIComponent(url.pathname.slice(1));file=path.normalize(file);const full=path.join(ROOT,file);if(!full.startsWith(ROOT)||!fs.existsSync(full)||fs.statSync(full).isDirectory())return error(res,404,'Archivo no encontrado');const adminPage=file==='admin.html';res.writeHead(200,{...securityHeaders,'Content-Type':mime[path.extname(full)]||'application/octet-stream','Cache-Control':adminPage?'no-store':'no-cache',...(adminPage?{'X-Robots-Tag':'noindex, nofollow, noarchive'}:{})});fs.createReadStream(full).pipe(res)}catch(e){console.error(e);error(res,e.status||500,e.status?e.message:'Error interno del servidor')}});
const PORT=Number(process.env.PORT)||8080;server.listen(PORT,'0.0.0.0',()=>{console.log(`Itzz Nails listo en 0.0.0.0:${PORT}`);console.log(`Ruta administrativa: ${ADMIN_ROUTE}`)});
